#!/usr/bin/env python3
"""
Assemble the main tweak translation unit for Theos.

Order (single TU so hook implementations can stay file-local `static`):
  1. Source/Runtime/THGlobalsAndHooking.m
  2. Source/Runtime/THNativeToast.m
  3. Source/Runtime/THSideloadFishhook.m
  4. Source/Runtime/THSubstrate.m
  5. Source/Hooks/**/*.m  (GIFNameOverlay.m first)
  6. Source/Runtime/THTweak.m

Output: TweakCOMPILE.xm
"""
from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "TweakCOMPILE.xm"

PRE = [
    ROOT / "Source/Runtime/THGlobalsAndHooking.m",
    ROOT / "Source/Runtime/THNativeToast.m",
    ROOT / "Source/SideloadNSE/ThetaHPKEKeyFile.m",
    ROOT / "Source/Runtime/THSideloadFishhook.m",
    ROOT / "Source/Runtime/THSubstrate.m",
]
POST = ROOT / "Source/Runtime/THTweak.m"
HOOKS = ROOT / "Source/Hooks"
PRIORITY = HOOKS / "UI" / "GIFNameOverlay.m"


def main() -> None:
    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/assemble.py — do not edit. */\n\n")

    for path in PRE:
        lines.extend(path.read_text(encoding="utf-8").splitlines(keepends=True))
        lines.append("\n")

    seen: set[str] = set()

    def append_hook(path: Path) -> None:
        ap = str(path.resolve())
        if ap in seen or not path.is_file():
            return
        seen.add(ap)
        chunk = path.read_text(encoding="utf-8").splitlines(keepends=True)
        if chunk and not chunk[-1].endswith("\n"):
            chunk[-1] += "\n"
        lines.extend(chunk)
        lines.append("\n")

    append_hook(PRIORITY)
    for dirpath, _, filenames in os.walk(HOOKS):
        for name in sorted(filenames):
            if name.endswith(".m"):
                append_hook(Path(dirpath) / name)

    lines.extend(POST.read_text(encoding="utf-8").splitlines(keepends=True))

    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes, {len(seen)} hook files)")


if __name__ == "__main__":
    main()
